### ISSUE TITLE
Config File \"config\" Not Found

### ISSUE THREAD

**Issue by bigzhu** [quailyquaily/quail-cli#1]
When first run, it throws this error:
```bash
❯ quail-cli login
2024/12/22 10:31:13 ERROR failed to read config error="Config File \"config\" Not Found in \"[/Users/bigzhu/.config/quail-cli]\"" config=/Users/bigzhu/.config/quail-cli/config.yaml
panic: Config File "config" Not Found in "[/Users/bigzhu/.config/quail-cli]"

goroutine 1 [running]:
github.com/quail-ink/quail-cli/cmd.initConfig()
        /Users/bigzhu/go/pkg/mod/github.com/quail-ink/quail-cli@v0.0.0-20240930062821-aa632cee8f68/cmd/root.go:80 +0x4a4
github.com/spf13/cobra.(*Command).preRun(...)
        /Users/bigzhu/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1019
github.com/spf13/cobra.(*Command).execute(0x1400016c308, {0x100df0da0, 0x0, 0x0})
        /Users/bigzhu/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:929 +0x424
github.com/spf13/cobra.(*Command).ExecuteC(0x100dc38e0)
        /Users/bigzhu/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/bigzhu/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /Users/bigzhu/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1034
github.com/quail-ink/quail-cli/cmd.ExecuteContext({0x100aba9a0?, 0x100df0da0?})
        /Users/bigzhu/go/pkg/mod/github.com/quail-ink/quail-cli@v0.0.0-20240930062821-aa632cee8f68/cmd/root.go:57 +0x58
main.main()
        /Users/bigzhu/go/pkg/mod/github.com/quail-ink/quail-cli@v0.0.0-20240930062821-aa632cee8f68/main.go:11 +0x2c
```
Manually creating a config.yaml file can bypass this error, but it feels bad and awkward.

**Comment by lyricat** [comment]
You're right. 
It should be created by cli. https://github.com/quail-ink/quail-cli/commit/3386997a651f033077fbe8fe4d413a76dea3d886
